[package]
name = "bober-rs"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "lexing",
    "pkb",
    "pql",
    "simple",
]

[dependencies]
simple = { path = "simple" }
lexing = { path = "lexing" }
pkb = { path = "pkb" }
pql = { path = "pql" }